name: Main CI
on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Run Spotless
        run: ./gradlew spotlessCheck

  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive .gradle folder
        uses: actions/upload-artifact@v4
        with:
          name: .gradle
          path: .gradle
      - name: Archive build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
      - name: Archive kex/build folder
        uses: actions/upload-artifact@v4
        with:
          name: kex_build
          path: kex/build

  publish:
    needs: build
    runs-on: macos-14
    if: github.ref == 'refs/heads/main'
    environment: Sonatype
    env:
      SONATYPE_GPG_KEY: ${{ secrets.SONATYPE_GPG_KEY }}
      SONATYPE_GPG_KEY_PASSWORD: ${{ secrets.SONATYPE_GPG_KEY_PASSWORD }}
      SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/main
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Download .gradle folder
        uses: actions/download-artifact@v4
        with:
          name: .gradle
      - name: Download build folder
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Download kex/build folder
        uses: actions/download-artifact@v4
        with:
          name: kex_build
      - name: Publish to Sonatype (Maven Central)
        shell: bash
        run: |
          brew install gnupg
          ./scripts/secret decrypt --password ${SECRETS_KEY}
          ./scripts/publish
